### ISSUE TITLE
ModuleNotFoundError: No module named 'vren'

### ISSUE THREAD

**Issue by Abbsalehi** [y-u-a-n-l-i/Climate_NeRF#8]
Thanks for your interesting work. I'm going to train using your sample dataset (TanksAndTempleBG), but I got the "ModuleNotFoundError: No module named 'vren' ". I could not find "vren" module to install.

```
(climatenerf) myuser@dell-3660:~/PycharmProjects/Climate_NeRF/scripts/tanks$ bash train.sh

/datasets/TanksAndTempleBG/Train
/mmsegmentation/ckpts/segformer_mit-b5_8xb1-160k_cityscapes-1024x1024.py
/mmsegmentation/ckpts/segformer_mit-b5_8x1_1024x1024_160k_cityscapes_20211206_072934-87a052ec.pth
ckpts/tnt/train/epoch=79_slim.ckpt
Traceback (most recent call last):
  File "/home/myuser/PycharmProjects/Climate_NeRF/train.py", line 20, in <module>
    from models.networks import NGP
  File "/home/myuser/PycharmProjects/Climate_NeRF/models/networks.py", line 6, in <module>
    import vren
ModuleNotFoundError: No module named 'vren'
Traceback (most recent call last):
  File "/home/myuser/PycharmProjects/Climate_NeRF/render.py", line 10, in <module>
    from models.networks import NGP
  File "/home/myuser/PycharmProjects/Climate_NeRF/models/networks.py", line 6, in <module>
    import vren
ModuleNotFoundError: No module named 'vren'
Traceback (most recent call last):
  File "/home/myuser/PycharmProjects/Climate_NeRF/render.py", line 10, in <module>
    from models.networks import NGP
  File "/home/myuser/PycharmProjects/Climate_NeRF/models/networks.py", line 6, in <module>
    import vren
ModuleNotFoundError: No module named 'vren'
Traceback (most recent call last):
  File "/home/myuser/PycharmProjects/Climate_NeRF/render.py", line 10, in <module>
    from models.networks import NGP
  File "/home/myuser/PycharmProjects/Climate_NeRF/models/networks.py", line 6, in <module>
    import vren
ModuleNotFoundError: No module named 'vren'

```

**Comment by y-u-a-n-l-i** [comment]
`vren` is the custom cuda extension that you can get after `pip install models/csrc`.

**Comment by Abbsalehi** [comment]
@y-u-a-n-l-i thanks alot, I installed it
